### PR TITLE
Plot functions for Occurrence BDP analysis

### PR DESCRIPTION
**Pull request by Jeremy-Andreoletti**
Hello, we have some plot functions associated with the Occurrence BDP in RevBayes (https://www.biorxiv.org/content/10.1101/2020.10.27.356758v1.full). Could we add them to RevGadgets?

### CODE REVIEW

**Comment by cmt2** [comment]
Hi @Jeremy-Andreoletti! Thanks for the contribution. We'v recently added a developers' guide [here](https://github.com/revbayes/RevGadgets/blob/development/developers_guide.md). Could you check that out and make sure that your code meets the RevGadgets guidelines? Specifically, it looks like you might need to create associated testing scripts. Let me know if you have any questions. I'm happy to help!

**Comment by Jeremy-Andreoletti** [comment]
Thanks @cmt2 for the developers' guide! It has made the instructions easier to follow, everything should be in conformity now. Please let me know if I've missed any points.

**Comment by Jeremy-Andreoletti** [comment]
I'm not sure why some of the ubuntu checks failed. I believe it is not related to my additions (e.g., I did not touch `ggimage`).

**Comment by cmt2** [comment]
Thanks @Jeremy-Andreoletti! The ggimage issue was due to some changes I've been trying to make so I went ahead and fixed that on my end. It all looks good now! Thanks again for your contribution.

**Comment by Jeremy-Andreoletti** [comment]
Great! Thanks for the merge :D

**Pull request merged**
